### ISSUE TITLE
Error with lbp and lbpm

### ISSUE THREAD

**Issue by bpstewar** [jgrss/spfeas#24]
I still cannot process lbp and lbpm triggers in the Docker process. I have updated the spfeas and mpglue libraries, but I still get the following errors. Any ideas? Is there a problem with my commands? With the image?

```
(base) root@2023cd9ab635:/data/input# spfeas -i spfeas_docker_sample_KIGALI.tif -tr mean lbpm -o sampleFAKE --sensor RGB --rgb
16:09:59:INFO:323:spfeas.main:
Start date & time --- (Fri Mar 30 16:09:59 2018)

16:10:00:INFO:541:sputilities.convert_rgb2gray:
Calculating average RGB ...

16:10:00:INFO:505:spsplit.get_section_stats:  Processing Mean for section 1 of 4 ...
16:10:00:INFO:26:spreshape.reshape_feature_list:  Reshaping features ...
16:10:00:INFO:57:spprocess._write_section2file:  Writing section 1 of 4 to file ...
16:10:00:INFO:541:sputilities.convert_rgb2gray:
Calculating average RGB ...

16:10:00:INFO:505:spsplit.get_section_stats:  Processing Mean for section 2 of 4 ...
16:10:00:INFO:26:spreshape.reshape_feature_list:  Reshaping features ...
16:10:00:INFO:57:spprocess._write_section2file:  Writing section 2 of 4 to file ...
16:10:00:INFO:541:sputilities.convert_rgb2gray:
Calculating average RGB ...

16:10:00:INFO:505:spsplit.get_section_stats:  Processing Mean for section 3 of 4 ...
16:10:00:INFO:26:spreshape.reshape_feature_list:  Reshaping features ...
16:10:00:INFO:57:spprocess._write_section2file:  Writing section 3 of 4 to file ...
16:10:00:INFO:541:sputilities.convert_rgb2gray:
Calculating average RGB ...

16:10:00:INFO:505:spsplit.get_section_stats:  Processing Mean for section 4 of 4 ...
16:10:00:INFO:26:spreshape.reshape_feature_list:  Reshaping features ...
16:10:00:INFO:57:spprocess._write_section2file:  Writing section 4 of 4 to file ...
16:10:00:INFO:602:spprocess.run:  Updating status ...
16:10:00:INFO:602:spprocess.run:  Updating status ...
16:10:00:INFO:541:sputilities.convert_rgb2gray:
Calculating average RGB ...

16:10:00:INFO:505:spsplit.get_section_stats:  Processing Local Binary Patterns moments for section 1 of 4 ...
Traceback (most recent call last):
  File "/opt/conda/envs/spfeasenv/bin/spfeas", line 11, in <module>
    load_entry_point('SpFeas==0.2.9', 'console_scripts', 'spfeas')()
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 361, in main
    overviews=args.overviews)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 164, in spatial_features
    spp.run()
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 155, in run
    spprocess.run(self)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spprocess.py", line 592, in run
    parallel_chunk_end))
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spprocess.py", line 365, in _section_read_write
    section_counter)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spsplit.py", line 514, in get_section_stats
    **other_args)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spsplit.py", line 146, in call_func
    return call_lbpm(block_array_, block_size_, scales_, end_scale_)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spsplit.py", line 104, in call_lbpm
    return _stats.feature_lbpm(block_array_, block_size_, scales_, end_scale_)
  File "spfeas/sphelpers/_stats.pyx", line 1851, in spfeas.sphelpers._stats.feature_lbpm
  File "spfeas/sphelpers/_stats.pyx", line 1814, in spfeas.sphelpers._stats._feature_lbpm
  File "spfeas/sphelpers/_stats.pyx", line 1704, in spfeas.sphelpers._stats._set_lbp
TypeError: only size-1 arrays can be converted to Python scalars
```

**Comment by jgrss** [comment]
Looking into this...

**Comment by jgrss** [comment]
I am going to close this issue because the scalar error is fixed. _However_, the output is still not correct so I will open a new issue.
