### ISSUE TITLE
SpFeas stacking error

### ISSUE THREAD

**Issue by pranabkrc** [jgrss/spfeas#30]
On running the SpFeas stacking command, 
spfeas -i City_Seg/Input/Bengaluru.tif -o City_Seg/Out/ --rgb --block 8 --scales 8 16 --stack-only

I am getting the following error:
Traceback (most recent call last):
  File "/home/pc6/anaconda3/envs/py27/bin/spfeas", line 11, in <module>
    load_entry_point('SpFeas==0.3.0b0', 'console_scripts', 'spfeas')()
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 447, in main
    overviews=args.overviews)
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 249, in spatial_features
    spp.run()
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 240, in run
    spprocess.run(self)
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/spprocess.py", line 431, in run
    parameter_object = sputilities.stack_features(parameter_object, new_feas_list)
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/sphelpers/sputilities.py", line 324, in stack_features
    parameter_object = scale_fea_check(parameter_object)
  File "/home/pc6/anaconda3/envs/py27/lib/python2.7/site-packages/SpFeas-0.3.0b0-py2.7-linux-x86_64.egg/spfeas/sphelpers/sputilities.py", line 266, in scale_fea_check
    section_counter_ = 'TL{:06}'.format(parameter_object.section_counter)
AttributeError: 'SPParameters' object has no attribute 'section_counter'

Could you please help with this?

**Comment by jgrss** [comment]
@pranabkrc There were some parameters that were missing when bypassing straight to VRT compositing. This should be fixed now--let me know if you are able to run it successfully.
