### ISSUE TITLE
Running spfeas on panchromatic imagery

### ISSUE THREAD

**Issue by bpstewar** [jgrss/spfeas#31]
Since you updated spfeas with the sensor parameter, I don't see how I can run spfeas on a single band grey image. Any suggestions?

I understand I won't be able to run the vegetation indices, but it errored on the seg trigger , which I didn't think would be a problem

**Comment by jgrss** [comment]
Try it now--I had the check for the satellite sensor in the wrong location.

**Comment by bpstewar** [comment]
So I should run it without the sensor flag at all? Rebuilding and testing again now

**Comment by bpstewar** [comment]
Still getting an error when it finishes ORB and moves onto seg

```
20:04:02:INFO:26:spreshape.reshape_feature_list:  Reshaping features ...
20:04:02:INFO:57:spprocess._write_section2file:  Writing section 448 of 448 to file ...
20:04:03:INFO:602:spprocess.run:  Updating status ...
20:04:04:INFO:602:spprocess.run:  Updating status ...
20:04:18:ERROR:605:raster_tools._check_band_list:  The requested band position cannot be greater than the image bands.

Traceback (most recent call last):
  File "/opt/conda/envs/spfeasenv/bin/spfeas", line 11, in <module>
    load_entry_point('SpFeas==0.2.9', 'console_scripts', 'spfeas')()
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 361, in main
    overviews=args.overviews)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 164, in spatial_features
    spp.run()
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spfeas.py", line 155, in run
    spprocess.run(self)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spprocess.py", line 592, in run
    parallel_chunk_end))
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/SpFeas-0.2.9-py2.7-linux-x86_64.egg/spfeas/spprocess.py", line 283, in _section_read_write
    cols=n_cols)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/MpGlue-0.1.9-py2.7-linux-x86_64.egg/mpglue/raster_tools.py", line 412, in read
    bands2open = self._check_band_list(bands2open)
  File "/opt/conda/envs/spfeasenv/lib/python2.7/site-packages/MpGlue-0.1.9-py2.7-linux-x86_64.egg/mpglue/raster_tools.py", line 606, in _check_band_list
    raise ValueError
ValueError
```
