### ISSUE TITLE
help

### ISSUE THREAD

**Issue by radhiachrt** [jgrss/spfeas#33]
I followed the steps of installing spfeas, but I get this error in test :
>>> import spfeas
>>> spfeas.test_features()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.egg\spfeas\test_spfeas.py", line 32, in test_features
 os.remove(test_features_dir)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\enig\\Anaconda3\\lib\\site-packages\\spfeas-0.3.4-py3.6-win-amd64.egg\\spfeas\\data\\features'
>>>
Can you help me to resolve this problem.
Thank you.

**Comment by jgrss** [comment]
Was this permissions issue resolved? It looks like you were at least able to execute `spfeas`, based on the other issue that you posted.

**Comment by radhiachrt** [comment]
No, this error appear when I test spfeas.test_features(), since import spfeas is running without error, i try to ignore it and test spfeas with my own image.

**Comment by kshanzz** [comment]
After many attempts, I found that manually deleting the features folder and running it again worked fine

This might have something to do with os.remove(test_features_dir) in test_spfeas.py, gpt told me I should change this to shutil.rmtree(test_features_dir), which worked, and I haven't encountered [WinError 5] since!

But after that, I still have problems, gpt and another issue related to the answer seems to explain that windows has limited support for multithreading, there will always be this and that error, after that, I changed to linux (ubuntu), test and so on, all successful!
