### ISSUE TITLE
spfeas error 

### ISSUE THREAD

**Issue by radhiachrt** [jgrss/spfeas#34]
please can you help me to overcome this error triggered when I use spfeas :

(base) C:\Windows\system32>spfeas -i C:\radhia\apriii.tif -o C:\radhia
17:45:50:INFO:409:spfeas.main:
Start date & time --- (Thu Oct 25 17:45:50 2018)

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\enig\Anaconda3\lib\multiprocessing\pool.py", line 119, in worke
r
    result = (True, func(*args, **kwds))
  File "C:\Users\enig\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapsta
r
    return list(map(*args))
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.e
gg\spfeas\spprocess.py", line 156, in _section_read_write
    section_pair = potsi[section_counter-1]
NameError: name 'potsi' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\enig\Anaconda3\Scripts\spfeas-script.py", line 11, in <module>
    load_entry_point('SpFeas==0.3.4', 'console_scripts', 'spfeas')()
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.e
gg\spfeas\spfeas.py", line 447, in main
    overviews=args.overviews)
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.e
gg\spfeas\spfeas.py", line 249, in spatial_features
    spp.run()
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.e
gg\spfeas\spfeas.py", line 240, in run
    spprocess.run(self)
  File "C:\Users\enig\Anaconda3\lib\site-packages\spfeas-0.3.4-py3.6-win-amd64.e
gg\spfeas\spprocess.py", line 622, in run
    parallel_chunk_end))
  File "C:\Users\enig\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\enig\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
NameError: name 'potsi' is not defined

(base) C:\Windows\system32>

**Comment by jgrss** [comment]
@radhiachrt Can you attach a subset of the image you are processing?

**Comment by radhiachrt** [comment]
I send you the image privately on your email.
thank you.

**Comment by jgrss** [comment]
The default parameters worked fine (on linux) applied to the image that you shared. Your issue might be specific to Windows. Try running it again, but add `--n-jobs 1`. I also added `--image-min 0 --image-max 300`. SpFeas expects float images to be in a 0-1 range, byte images as 0-255, and unsigned 16-bit images as 0-10,000. Since your image is stored as float, SpFeas scales it thinking the maximum is 1, but your histogram shows the tail is around 300.
